# Generated by Django 4.2.11 on 2024-05-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user', to_field='username'),
        )

    ]
