# Generated by Django 4.2.11 on 2024-05-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_task_publisher_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user', to_field='username'),
        ),
    ]
