# Generated by Django 4.2.11 on 2024-05-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_task_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
