# Generated by Django 4.2.11 on 2024-05-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_task_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user', to_field='username'),
        ),
    ]
