# Generated by Django 4.2.11 on 2024-06-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_task_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user', to_field='username'),
        ),
    ]
