# Generated by Django 4.2.11 on 2024-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_subtask_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
