# Generated by Django 4.2.11 on 2024-06-01 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_task_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCreditRank',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
